In [ ]:
'''
Pandas mainly used for data manipulation
kindly similar to SQL
'''
!mamba install matplotlib   #used for online jupyter tabs

In [1]:
!pip install matplotlib              #able to create a visual charts

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in /usr/lib/python3/dist-packages (3.5.1)

In [3]:
import numpy as np   #used to perform numerical operation
import pandas as pd  #used for data manipulation
import matplotlib.pyplot as plt  #used for the data visualization

Data loading

In [3]:
data=pd.read_csv("order.csv")
data.head()

,order_id,user_id,restaurant_id,order_date,total_amount,items_ordered,payment_method,order_status,name_user,gender,city_user,name_restaurant,city_restaurant,avg_cost_for_two,rating,delivery_pertner_pay,delivery_time_min
0,ORD0001,USR002,RST007,01/04/2024,2188,"Fried Rice, Masala Dosa, Hakka Noodles",Credit Card,Completed,Damini Lal,Female,Kolkata,Fusion Flavors #7,Kolkata,260,3.1,153.16,60.0
1,ORD1933,USR080,RST007,26/03/2025,846,"Chicken Biryani, Dal Makhani, Mutton Rogan Josh",Wallet,Completed,Ela Dubey,Female,Kolkata,Fusion Flavors #7,Kolkata,260,3.1,59.22,50.0
2,ORD1946,USR038,RST007,28/03/2025,1431,"Chole Bhature, Aloo Tikki, Samosa",Cash on Delivery,Completed,Riaan Thaker,Male,Kolkata,Fusion Flavors #7,Kolkata,260,3.1,100.17,80.0
3,ORD1265,USR102,RST007,21/11/2024,1231,"Butter Naan, Chicken Curry, Aloo Tikki, Masala...",Wallet,Completed,Vihaan Som,Male,Kolkata,Fusion Flavors #7,Kolkata,260,3.1,86.17,60.0
4,ORD1694,USR124,RST007,09/02/2025,523,"Butter Naan, Chole Bhature, Pav Bhaji",UPI,Completed,Riaan Kata,Male,Kolkata,Fusion Flavors #7,Kolkata,260,3.1,36.61,100.0

Question1: Which payment method is highly prefered by customers?

In [4]:
data["payment_method"]  
#All details are given but we need the specific payment

0            Credit Card
1                 Wallet
2       Cash on Delivery
3                 Wallet
4                    UPI
              ...
1963                 UPI
1964                 UPI
1965    Cash on Delivery
1966                 UPI
1967                 UPI
Name: payment_method, Length: 1968, dtype: object

In [5]:
data["payment_method"].value_counts()
#find the count of each and every payment

payment_method
Cash on Delivery    514
UPI                 511
Wallet              495
Credit Card         448
Name: count, dtype: int64

In [9]:
data["payment_method"].value_counts().plot(
                                     kind="pie",  
                                     autopct="%.2f%%",
                                     explode=(0.1,0,0,0)
                                     )

NameError: name 'data' is not defined

Question2: Payment_method by city wise #in which city the payment method is high

In [10]:
data.groupby("city_user")["payment_method"].value_counts()

NameError: name 'data' is not defined

In [13]:
import pandas as pd
data=pd.read_csv("order.csv")
data.head()
data.groupby("city_user")["payment_method"].value_counts()

city_user  payment_method
Ahmedabad  Wallet              59
           Cash on Delivery    53
           UPI                 51
           Credit Card         45
Bangalore  UPI                 69
           Cash on Delivery    58
           Wallet              57
           Credit Card         52
Chennai    Wallet              81
           UPI                 70
           Cash on Delivery    69
           Credit Card         58
Delhi      Cash on Delivery    70
           UPI                 61
           Wallet              61
           Credit Card         58
Hyderabad  Cash on Delivery    74
           UPI                 70
           Wallet              66
           Credit Card         54
Kolkata    Cash on Delivery    94
           UPI                 80
           Credit Card         78
           Wallet              74
Mumbai     UPI                 64
           Wallet              62
           Credit Card         59
           Cash on Delivery    56
Pune       UPI                 46
           Credit Card         44
           Cash on Delivery    40
           Wallet              35
Name: count, dtype: int64

In [14]:
(data.groupby("city_user")["payment_method"].value_counts()
                                            .reset_index()
)

    city_user    payment_method  count
0   Ahmedabad            Wallet     59
1   Ahmedabad  Cash on Delivery     53
2   Ahmedabad               UPI     51
3   Ahmedabad       Credit Card     45
4   Bangalore               UPI     69
5   Bangalore  Cash on Delivery     58
6   Bangalore            Wallet     57
7   Bangalore       Credit Card     52
8     Chennai            Wallet     81
9     Chennai               UPI     70
10    Chennai  Cash on Delivery     69
11    Chennai       Credit Card     58
12      Delhi  Cash on Delivery     70
13      Delhi               UPI     61
14      Delhi            Wallet     61
15      Delhi       Credit Card     58
16  Hyderabad  Cash on Delivery     74
17  Hyderabad               UPI     70
18  Hyderabad            Wallet     66
19  Hyderabad       Credit Card     54
20    Kolkata  Cash on Delivery     94
21    Kolkata               UPI     80
22    Kolkata       Credit Card     78
23    Kolkata            Wallet     74
24     Mumbai               UPI     64
25     Mumbai            Wallet     62
26     Mumbai       Credit Card     59
27     Mumbai  Cash on Delivery     56
28       Pune               UPI     46
29       Pune       Credit Card     44
30       Pune  Cash on Delivery     40
31       Pune            Wallet     35

Question3: Total revenue by city

In [27]:
(data.groupby("city_user")["total_amount"].sum()
    .sort_values(ascending=False)
)

city_user
Kolkata      490524
Hyderabad    410855
Chennai      408574
Delhi        397304
Mumbai       394955
Bangalore    377148
Ahmedabad    330653
Pune         239715
Name: total_amount, dtype: int64

In [21]:
(data.groupby("city_user")["total_amount"].sum()
    .sort_values(ascending=False)
     colour="skyblue"
)

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (287375950.py, line 3)

File handling

<h3 style="color:red"><i>File handling</i></h3>

<h3 style="color:skyblue"><i>File handling</i></h3>

In [ ]:
'''File-used for data storing
File handling is a concept where we can create,read and write a file.
File operation modes:
'w'-write
'r'-read
'a'-append
'w+'-write and read
'r+'-read and write
'''

In [33]:
with open("sample.txt","w") as file:
    file.write("\nHey there!")

In [34]:
with open("sample.txt","a") as file:
    file.write("\nHey! this is sample txt")

In [35]:
with open("sample.txt","a") as file:
    file.write("\nHey there!")

In [36]:
with open("sample.txt","w") as file:
    file.writelines('''
    okay everything is cool here
    file handling is good to use
    when we have less data
    ''')

In [38]:
with open("sample.txt","r") as file:
    data=file.read()
    print(data)

    okay everything is cool here
    file handling is good to use
    when we have less data

In [43]:
with open("demo1.txt","w+") as file:
    file.writelines('''    
    Hey there!,
    This is sample text file!,
    Hurray!!!!
    ''')
    file.seek(0)      #it points to the current cursor
    data=file.read()
print(data)

    Hey there!,
    This is sample text file!,
    Hurray!!!!

### FILE READING

''''''''''''
file operation mode
'w'-write
'r'-read
'a'-append
'w+'-write and read
'r+'-read and write
'x'-open file in exclusive mode(throw error if file already exists)
'rb'-reading the byte data
'wb'-writing byte data

1.write()
2.writelines()
3.read()
4.readlines()
5.seek()-pointer movement
6.tell()-pointer position
''''''''

In [44]:
file=open("sample.txt",'r')
data=file.read()
file.close()
print(data)

    okay everything is cool here
    file handling is good to use
    when we have less data

In [45]:
with open("sample.txt","r")as file:
    file.seek(20)#
    print(file.tell())#get the pointer location

20

In [46]:
import os
FILE_NAME="sample.txt"
if os.path.exists(FILE_NAME):
    print("file name already there,create a new one")

file name already there,create a new one