Pandas

In [ ]:
'''
Pandas-Mainly used by data analyst                                   
data - raw facts
information - providing meaning to the data

Name Dept marks
Ashika Cse 95
Aravinth BBA 96

1.SQL-Table format
2.Excel file
3.Text file
4.CSV file

pandas - used for data manipulation(READ,UPDATE,CREATE,)
csv-Comma seperated value 
dataframe
series

'''
1.open notepad
2.types values seperated by commas
3.Ctrl+s to save file with name sample.csv
4.after save,open with excel

In [1]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-2.3.3-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 31.8 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Collecting python-dateutil>=2.8.2
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 KB 23.2 MB/s eta 0:00:00
Collecting tzdata>=2022.7
  Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 348.2/348.2 KB 30.4 MB/s eta 0:00:00
Collecting numpy>=1.22.4
  Downloading numpy-2.2.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 24.8 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Installing collected packages: tzdata, python-dateutil, numpy, pandas
  WARNING: The scripts f2py and numpy-config are installed in '/home/smce-sw/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed numpy-2.2.6 pandas-2.3.3 python-dateutil-2.9.0.post0 tzdata-2026.3

In [1]:
import pandas as pd

In [ ]:
'''in pandas:
 1.Series - one row/one column
 2.Data frame - table format
 '''

In [7]:
import pandas as pd
df=pd.DataFrame({
    "Name":["Jack","Alex","Sofia"],
    "Department":["CSE","CSE","CSE"],
    "CGPA":[9.2,8,7]
})
print(df)

ModuleNotFoundError: No module named 'pandas'

In [4]:
df=pd.DataFrame({
    "Name":["Jack","Alex","Sofia"],
    "Department":["CSE","CSE","CSE"],
    "CGPA":[9.2,8,7]
})
print(df)

    Name Department  CGPA
0   Jack        CSE   9.2
1   Alex        CSE   8.0
2  Sofia        CSE   7.0

In [45]:
import pandas as pd
df=pd.DataFrame({
    "Name":["Ashika","Aravinth","Amutha"],
    "Department":["CSE","BBA","CSE"],
    "CGPA":[9.2,8,7],
    "Email":["123@gmail.com","123@gmail.com","143@gmail.com"]
})
print(df)

       Name Department  CGPA          Email
0    Ashika        CSE   9.2  123@gmail.com
1  Aravinth        BBA   8.0  123@gmail.com
2    Amutha        CSE   7.0  143@gmail.com

In [6]:
df["Name"].ndim #One dimensional

1

In [10]:
df[["Name"]].ndim #Two dimensional

2

In [11]:
f=67
f

67

In [46]:
df["CGPA"]>9

0     True
1    False
2    False
Name: CGPA, dtype: bool

In [48]:
df[df["CGPA"]>9]

     Name Department  CGPA          Email
0  Ashika        CSE   9.2  123@gmail.com

In [47]:
df[df["CGPA"]>=8]

       Name Department  CGPA          Email
0    Ashika        CSE   9.2  123@gmail.com
1  Aravinth        BBA   8.0  123@gmail.com

In [52]:
df[(df["CGPA"]>=6)&(df["Email"]=="143@gmail.com")]

     Name Department  CGPA          Email
2  Amutha        CSE   7.0  143@gmail.com

In [51]:
df[(df["CGPA"]>=8)&(df["Email"]=="123@gmail.com")]

       Name Department  CGPA          Email
0    Ashika        CSE   9.2  123@gmail.com
1  Aravinth        BBA   8.0  123@gmail.com

In [60]:
df[(df["CGPA"]<8)]

     Name Department  CGPA          Email
2  Amutha        CSE   7.0  143@gmail.com

In [59]:
df[df["CGPA"]>=7]

       Name Department  CGPA          Email
0    Ashika        CSE   9.2  123@gmail.com
1  Aravinth        BBA   8.0  123@gmail.com
2    Amutha        CSE   7.0  143@gmail.com

In [62]:
type(df["Name"])

pandas.core.series.Series

In [64]:
df.shape

(3, 4)

In [65]:
df.columns

Index(['Name', 'Department', 'CGPA', 'Email'], dtype='object')

In [68]:
a=int(input("Enter the number:"))
b=int(input("Enter the number:"))
c=a+b
c

Enter the number:45
Enter the number:54

99

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        3 non-null      object
 1   Department  3 non-null      object
 2   CGPA        3 non-null      float64
 3   Email       3 non-null      object
dtypes: float64(1), object(3)
memory usage: 224.0+ bytes

In [72]:
df.dtypes

Name           object
Department     object
CGPA          float64
Email          object
dtype: object

Missing values
    -Not a Number(NaN)

In [75]:
df.isna().sum()
# isnull is also used to find whether the missing value is having or not

Name          0
Department    0
CGPA          0
Email         0
dtype: int64

In [80]:
import numpy as np
df2=pd.DataFrame({
    "order_id":["1003","1004","1005"],
    "location":["MAS",np.nan,"ED"],
    "amount":[2000,3000,8000]
})
df2

  order_id location  amount
0     1003      MAS    2000
1     1004      NaN    3000
2     1005       ED    8000

In [81]:
import numpy as np
df2=pd.DataFrame({
    "order_id":["1003","1004",np.nan],
    "location":["MAS",np.nan,"ED"],
    "amount":[2000,3000,8000]
})
df2

  order_id location  amount
0     1003      MAS    2000
1     1004      NaN    3000
2      NaN       ED    8000

In [82]:
import numpy as np
df2=pd.DataFrame({
    "order_id":["1003","1004",np.nan],
    "location":["MAS",np.nan,"ED"],
    "amount":[np.nan,3000,8000]
})
df2

  order_id location  amount
0     1003      MAS     NaN
1     1004      NaN  3000.0
2      NaN       ED  8000.0

In [83]:
df2["order_id"].fillna("10034",inplace=True)

/tmp/ipykernel_7924/2193855791.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2["order_id"].fillna("10034",inplace=True)

In [84]:
df2["location"].fillna("cbe",inplace=True)

/tmp/ipykernel_7924/1071415416.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2["location"].fillna("cbe",inplace=True)

In [ ]:
'''
loc-label based indexing
Syntx:df.loc[row,col]
iloc-integer based indexing
'''

In [85]:
df2

  order_id location  amount
0     1003      MAS     NaN
1     1004      cbe  3000.0
2    10034       ED  8000.0

In [88]:
df2.loc[:,"order_id"] #all row+order_id columns

0     1003
1     1004
2    10034
Name: order_id, dtype: object

In [90]:
df2.loc[:1,:"location"]

  order_id location
0     1003      MAS
1     1004      cbe

In [91]:
df2.iloc[1:3,1]

1    cbe
2     ED
Name: location, dtype: object

In [92]:
df2.iloc[1:3,1:2]

  location
1      cbe
2       ED

In [93]:
df2.iloc[0,1]

'MAS'

In [94]:
df2.iloc[0,1]="Chennai"

In [96]:
for i in range(5):
    for j in range(2):
        print(i,j)

0 0
0 1
1 0
1 1
2 0
2 1
3 0
3 1
4 0
4 1

In [105]:
import pandas as pd
df=pd.read_csv("order.csv")
df.head()
df.head(2)
df.tail()
df.tail()
df.tail(2)
df.sample()
df.sample(2)

,order_id,user_id,restaurant_id,order_date,total_amount,items_ordered,payment_method,order_status,name_user,gender,city_user,name_restaurant,city_restaurant,avg_cost_for_two,rating,delivery_pertner_pay,delivery_time_min
1148,ORD1221,USR188,RST001,09/11/2024,1957,"Butter Naan, Masala Dosa, Paneer Butter Masala...",Wallet,Completed,Advik Bhatti,Male,Hyderabad,Spicy Bites #1,Hyderabad,490,4.3,136.99,60.0
405,ORD0126,USR130,RST045,26/04/2024,0,"Masala Dosa, Pav Bhaji, Idli Sambhar",Cash on Delivery,Cancelled,Oorja Shankar,Female,Kolkata,Spicy Kitchen #45,Kolkata,372,3.4,160.79,60.0

In [106]:
import pandas as pd
df=pd.read_csv("order.csv")
df

,order_id,user_id,restaurant_id,order_date,total_amount,items_ordered,payment_method,order_status,name_user,gender,city_user,name_restaurant,city_restaurant,avg_cost_for_two,rating,delivery_pertner_pay,delivery_time_min
0,ORD0001,USR002,RST007,01/04/2024,2188,"Fried Rice, Masala Dosa, Hakka Noodles",Credit Card,Completed,Damini Lal,Female,Kolkata,Fusion Flavors #7,Kolkata,260,3.1,153.16,60.0
1,ORD1933,USR080,RST007,26/03/2025,846,"Chicken Biryani, Dal Makhani, Mutton Rogan Josh",Wallet,Completed,Ela Dubey,Female,Kolkata,Fusion Flavors #7,Kolkata,260,3.1,59.22,50.0
2,ORD1946,USR038,RST007,28/03/2025,1431,"Chole Bhature, Aloo Tikki, Samosa",Cash on Delivery,Completed,Riaan Thaker,Male,Kolkata,Fusion Flavors #7,Kolkata,260,3.1,100.17,80.0
3,ORD1265,USR102,RST007,21/11/2024,1231,"Butter Naan, Chicken Curry, Aloo Tikki, Masala...",Wallet,Completed,Vihaan Som,Male,Kolkata,Fusion Flavors #7,Kolkata,260,3.1,86.17,60.0
4,ORD1694,USR124,RST007,09/02/2025,523,"Butter Naan, Chole Bhature, Pav Bhaji",UPI,Completed,Riaan Kata,Male,Kolkata,Fusion Flavors #7,Kolkata,260,3.1,36.61,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1963,ORD1068,USR125,RST073,12/10/2024,2359,"Chicken Biryani, Chicken Curry, Dal Makhani",UPI,Completed,Hazel Bali,Female,Pune,Tasty Kitchen #73,Pune,429,4.9,165.13,50.0
1964,ORD0429,USR194,RST073,17/06/2024,0,"Butter Naan, Chicken Curry, Veg Pulao",UPI,Cancelled,Kashvi Sahota,Female,Pune,Tasty Kitchen #73,Pune,429,4.9,137.55,40.0
1965,ORD1438,USR194,RST073,23/12/2024,1879,"Dal Makhani, Aloo Tikki",Cash on Delivery,Completed,Kashvi Sahota,Female,Pune,Tasty Kitchen #73,Pune,429,4.9,131.53,60.0
1966,ORD1325,USR090,RST073,01/12/2024,1397,"Samosa, Mutton Rogan Josh, Veg Pulao, Chicken ...",UPI,Completed,Faiyaz Loke,Male,Pune,Tasty Kitchen #73,Pune,429,4.9,97.79,100.0
1967,ORD1968,USR145,RST046,2025-05-28,560,"Burger, Coke",UPI,Completed,Sivaraman T,Male,Chennai,Spicy Grill #46,Chennai,400,4.4,39.20,40.0